services:

  src:
    build: ./docker
    volumes:
    - logs:/shared
    - ./test/nginx/.htpasswd:/etc/nginx/sites-enabled/.htpasswd:ro
    - ./test/nginx/index/www:/var/www/index:ro
    - ./test/nginx/index/nginx.conf:/etc/nginx/sites-enabled/index.conf:ro
    - ./test/nginx/logs/www:/var/www/logs:ro
    - ./test/nginx/logs/nginx.conf:/etc/nginx/sites-enabled/logs.conf:ro
    - ./test/nginx/rewrite/nginx.conf:/etc/nginx/sites-enabled/rewrite.conf:ro
    - ./test/nginx/status/www:/var/www/status:ro
    - ./test/nginx/status/nginx.conf:/etc/nginx/sites-enabled/status.conf:ro
    - ./test/nginx/try_files/www:/var/www/try_files:ro
    - ./test/nginx/try_files/nginx.conf:/etc/nginx/sites-enabled/try_files.conf:ro
    ports:
    - 80:80
    networks:
      default:
        aliases:
        - fake.local
        - index.local
        - logs.local
        - obsolete.local
        - proxy_pass.local
        - proxy_redirect.local
        - status.local
        - try_files.local
        - rewrite.local
        - www.rewrite.local

  test:
    depends_on:
    - src
    image: node:16-alpine
    command: tail -f /dev/null
    working_dir: /app
    volumes:
    - logs:/shared
    - ./package.json:/app/package.json:ro
    - ./test/mocha:/app/test/mocha:ro

volumes:
  logs:
