name: Test
on:
  push:
    branches:
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Build
      run: |
        docker-compose build src -f ./docker-compose.test.yml
        docker-compose up -f ./docker-compose.test.yml -d

    - name: Test
      run: |
        docker-compose exec -f ./docker-compose.test.yml -T test npm install --prefer-offline --no-audit --no-fund --no-update-notifier
        docker-compose exec -f ./docker-compose.test.yml -T test npm run test

    - name: Cleanup
      run: docker-compose down -f ./docker-compose.test.yml --volumes
      if: always()
